### ISSUE TITLE
Previously 'on' notes keep playing even after Stop is clicked.

### ISSUE THREAD

**Issue by kaushalsali** [Aavu/MIDI-Editor#10]
**Description:** If you stop the playback and restart it, notes which were playing when you clicked stop are continued. Related to issue #9 

**Possible reason:** `noteOff` messages get skipped for the notes that were playing due to scrubbing.

**Possible solution:** Clear and reload the the Midi Buffer passed to the Synth.

**Comment by Aavu** [comment]
Fixed note on tails. Note off is fired on all channels when scrolling.

**Comment by kaushalsali** [comment]
This issue still exists.

**Comment by Aavu** [comment]
Fixed in #20
